name: Approval Workflow
on: [pull_request_review]
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: abinoda/label-when-approved-action@1.0.5
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "hacktoberfest-approved"
        REMOVE_LABEL: "awaiting%20review"
